pipeline {
  agent any

  environment {
    SSH_KEY_ID = 'cle-ssh-jenkins'
    REMOTE_HOST = '4.206.99.81'
    REMOTE_USER = 'azureuser'
    REMOTE_DIR  = '/opt/wikijs-deploy'
  }

  stages {
    stage('Préparer accès GitHub') {
      steps {
        sshagent (credentials: [env.SSH_KEY_ID]) {
          sh '''
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          '''
        }
      }
    }

    stage('Déployer sur la VM') {
      steps {
        sshagent (credentials: [env.SSH_KEY_ID]) {
          sh """
            ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} << 'EOF'
              cd ${REMOTE_DIR} || (
                sudo mkdir -p ${REMOTE_DIR} &&
                sudo chown -R ${REMOTE_USER}:${REMOTE_USER} ${REMOTE_DIR} &&
                cd ${REMOTE_DIR} &&
                git init &&
                git remote add origin git@github.com:Hanane-Chaouche/multisitjenkins.git
              )

              git config --global --add safe.directory ${REMOTE_DIR}
              git pull origin main

              docker compose -f instances/wiki1/docker-compose.yml up -d
              docker compose -f instances/wiki2/docker-compose.yml up -d
              docker compose -f instances/wiki-public/docker-compose.yml up -d
              docker compose -f nginx/docker-compose.yml up -d
            EOF
          """
        }
      }
    }
  }
}
